### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by vadrian89**
I have added the openweathermap api, changed info in the credit page and some small refactoring code changing, but there is an issue which makes it unfit for broad audience.  
The select isn't showing the correctly, I have looked a bit on the internet and you might need to add some python code to be properly shown....I will mail you a screenshot with the issue to be more visible.

### CODE REVIEW

**Comment by archisman-panigrahi** [comment]
@vadrian89 Could you please upload a screenshot? You may not be able to select it as .apiselect it has not been added to disabledrag list in script.js line no 55

**Comment by archisman-panigrahi** [comment]
There is a bug in this pull. Weather is reloaded as soon as Source is selected.

**Comment by vadrian89** [comment]
Ok, thank you, I will upload as soon as I am able.

**Comment by vadrian89** [comment]
About the bug, it is intended that way, just I didn't thought about all situations :D, I will change the behaviour in next commit / pull. Thanks for all the feedback.

Edit: "it is intended that way", I thought that it should update the data right after the api change, didn't thought the user might want to change other info :D

**Comment by vadrian89** [comment]
Daryl, do not merge this request until we fix the select issue.
Thanks.

**Comment by vadrian89** [comment]
Now the api can be selected, but I cannot target the background of the select. Should I change the color of the font to black and leave it so for now?

**Comment by vadrian89** [comment]
[Screenshot side be side: browser / application](https://drive.google.com/open?id=0B4ol_ScA7c2nUExTN1EzQ0JLM00)

**Comment by vadrian89** [comment]
Implemented fixes.  
[Api selection](https://drive.google.com/open?id=0B4ol_ScA7c2nNzZILWVhNmo2YUE)

**Comment by kd8bny** [comment]
Are we good to merge this pull request now?

**Comment by vadrian89** [comment]
Panigrahi, is it ok with you for merging?  
By me is ok.

**Pull request merged**
